import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Activity, User, Mail, FileText, ChevronRight,
  CheckCircle2, AlertCircle, BarChart3, Sparkles, ClipboardList,
} from 'lucide-react';
import { api } from '@/lib/api-client';
import { Button } from '@/components/ui/button';

const INPUT_CLS =
  'w-full h-9 px-3 text-sm border border-border-col rounded-md bg-bg-surface ' +
  'focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary ' +
  'text-text-primary placeholder:text-text-muted';

const LABEL_CLS = 'block text-xs font-semibold text-text-secondary mb-1.5 uppercase tracking-wide';

export function RegisterPage() {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    full_name: '',
    username: '',
    email: '',
    requested_role: 'viewer' as 'analyst' | 'viewer',
    reason: '',
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);

  const set = (key: keyof typeof form) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) =>
      setForm(prev => ({ ...prev, [key]: e.target.value }));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      await api.post('/auth/register', {
        ...form,
        reason: form.reason.trim() || undefined,
      });
      setSuccess(true);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Registration failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex">
      {/* ── Left panel ── */}
      <div className="hidden lg:flex lg:w-[44%] flex-col justify-between relative overflow-hidden
                      bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-10">
        {/* Dot grid */}
        <div
          className="absolute inset-0 opacity-[0.04] pointer-events-none"
          style={{ backgroundImage: 'radial-gradient(circle, #fff 1px, transparent 1px)', backgroundSize: '24px 24px' }}
        />
        <div className="relative">
          <div className="flex items-center gap-3 mb-16">
            <div className="w-10 h-10 bg-primary rounded-xl flex items-center justify-center shadow-lg">
              <Activity className="w-6 h-6 text-white" />
            </div>
            <div>
              <p className="text-white font-semibold text-sm leading-tight">OEE Intelligence</p>
              <p className="text-slate-400 text-xs">Enphase Energy</p>
            </div>
          </div>

          <h2 className="text-3xl font-bold text-white leading-snug mb-4">
            Manufacturing<br />Intelligence Platform
          </h2>
          <p className="text-slate-400 text-sm leading-relaxed mb-10">
            Request access to the OEE platform and start making data-driven decisions on the factory floor.
          </p>

          <div className="space-y-5">
            {[
              {
                icon: BarChart3,
                title: 'Real-time OEE Tracking',
                desc: 'Monitor Availability, Performance, and Quality across all production lines.',
              },
              {
                icon: Sparkles,
                title: 'AI-Powered Insights',
                desc: 'Automated root cause analysis and action plans generated by AI.',
              },
              {
                icon: ClipboardList,
                title: 'Actionable Reporting',
                desc: 'Weekly summaries, downtime Pareto charts, and equipment health scoring.',
              },
            ].map(({ icon: Icon, title, desc }) => (
              <div key={title} className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-lg bg-primary/20 border border-primary/30 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <Icon className="w-4 h-4 text-blue-400" />
                </div>
                <div>
                  <p className="text-white text-sm font-medium">{title}</p>
                  <p className="text-slate-400 text-xs mt-0.5 leading-relaxed">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <p className="relative text-slate-600 text-xs">
          © {new Date().getFullYear()} Enphase Energy · Manufacturing Operations
        </p>
      </div>

      {/* ── Right panel ── */}
      <div className="flex-1 flex items-center justify-center p-6 bg-bg-base overflow-y-auto">
        <div className="w-full max-w-md">

          {/* Mobile logo */}
          <div className="flex lg:hidden items-center gap-2 justify-center mb-8">
            <div className="w-9 h-9 bg-primary rounded-xl flex items-center justify-center">
              <Activity className="w-5 h-5 text-white" />
            </div>
            <p className="text-base font-semibold text-text-primary">OEE Intelligence Platform</p>
          </div>

          {success ? (
            /* ── Success state ── */
            <div className="card p-8 text-center">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-success-light mb-4">
                <CheckCircle2 className="w-8 h-8 text-success" />
              </div>
              <h2 className="text-xl font-bold text-text-primary mb-2">Request Submitted!</h2>
              <p className="text-text-muted text-sm mb-1">Your access request has been received.</p>
              <p className="text-text-muted text-sm mb-6">
                You'll be notified once an admin approves your access.
              </p>
              <button
                onClick={() => navigate('/login')}
                className="text-primary text-sm hover:underline flex items-center gap-1 justify-center"
              >
                Back to Login <ChevronRight className="w-3.5 h-3.5" />
              </button>
            </div>
          ) : (
            /* ── Form ── */
            <div className="card p-8">
              <h2 className="text-xl font-bold text-text-primary mb-1">Request Access</h2>
              <p className="text-text-muted text-sm mb-6">Fill in your details and an admin will review your request.</p>

              {error && (
                <div className="flex items-center gap-2 p-3 bg-red-50 text-danger rounded-md mb-5 text-sm">
                  <AlertCircle className="w-4 h-4 flex-shrink-0" />
                  <span>{error}</span>
                </div>
              )}

              <form onSubmit={handleSubmit} className="space-y-4">
                {/* Full Name */}
                <div>
                  <label className={LABEL_CLS}>Full Name</label>
                  <div className="relative">
                    <User className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted" />
                    <input
                      type="text"
                      value={form.full_name}
                      onChange={set('full_name')}
                      placeholder="Jane Smith"
                      required
                      minLength={2}
                      maxLength={100}
                      className={INPUT_CLS + ' pl-9'}
                    />
                  </div>
                </div>

                {/* Username */}
                <div>
                  <label className={LABEL_CLS}>Username</label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted text-sm font-mono">@</span>
                    <input
                      type="text"
                      value={form.username}
                      onChange={set('username')}
                      placeholder="jane_smith"
                      required
                      minLength={3}
                      maxLength={50}
                      pattern="^[a-zA-Z0-9_]+$"
                      title="Letters, numbers and underscores only"
                      className={INPUT_CLS + ' pl-7'}
                    />
                  </div>
                  <p className="text-[11px] text-text-muted mt-1">Letters, numbers and underscores only</p>
                </div>

                {/* Email */}
                <div>
                  <label className={LABEL_CLS}>Email Address</label>
                  <div className="relative">
                    <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted" />
                    <input
                      type="email"
                      value={form.email}
                      onChange={set('email')}
                      placeholder="jane@company.com"
                      required
                      className={INPUT_CLS + ' pl-9'}
                    />
                  </div>
                </div>

                {/* Access Level */}
                <div>
                  <label className={LABEL_CLS}>Access Level</label>
                  <div className="grid grid-cols-2 gap-2">
                    {([
                      {
                        value: 'analyst',
                        label: 'Analyst',
                        desc: 'Upload data, run AI analysis, manage action plans',
                      },
                      {
                        value: 'viewer',
                        label: 'Viewer',
                        desc: 'View dashboards and reports (read-only)',
                      },
                    ] as const).map(opt => (
                      <label
                        key={opt.value}
                        className={`flex flex-col gap-1 p-3 rounded-lg border cursor-pointer transition-colors ${
                          form.requested_role === opt.value
                            ? 'border-primary bg-primary/5'
                            : 'border-border-col hover:border-primary/40'
                        }`}
                      >
                        <div className="flex items-center gap-2">
                          <input
                            type="radio"
                            name="requested_role"
                            value={opt.value}
                            checked={form.requested_role === opt.value}
                            onChange={set('requested_role')}
                            className="accent-primary"
                          />
                          <span className="text-sm font-semibold text-text-primary">{opt.label}</span>
                        </div>
                        <p className="text-[11px] text-text-muted leading-snug pl-5">{opt.desc}</p>
                      </label>
                    ))}
                  </div>
                </div>

                {/* Reason */}
                <div>
                  <label className={LABEL_CLS}>
                    Reason for Access <span className="text-text-disabled font-normal normal-case tracking-normal">(optional)</span>
                  </label>
                  <div className="relative">
                    <FileText className="absolute left-3 top-2.5 w-4 h-4 text-text-muted" />
                    <textarea
                      value={form.reason}
                      onChange={set('reason')}
                      placeholder="Briefly describe why you need access..."
                      maxLength={500}
                      rows={3}
                      className={INPUT_CLS + ' pl-9 h-auto py-2 resize-none'}
                    />
                  </div>
                  <p className="text-[11px] text-text-muted mt-1 text-right">{form.reason.length}/500</p>
                </div>

                <Button type="submit" className="w-full" disabled={loading}>
                  {loading ? 'Submitting...' : 'Request Access'}
                </Button>
              </form>

              <div className="mt-5 pt-4 border-t border-border-col text-center">
                <p className="text-xs text-text-muted">
                  Already have access?{' '}
                  <button onClick={() => navigate('/login')} className="text-primary hover:underline font-medium">
                    Sign in
                  </button>
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
